config/routes.rb
Fatwallet::Application.routes.draw do

  match "/stores/favorites" => "stores#favorites"

  resources :stores

  devise_for :users

  resources :posts

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :name, :title
end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :cashback, :company
  has_many :store_favorites
  has_many :users, :through => :store_favorites
 
  
end

app/models/store_favorite.rb
class StoreFavorite < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  belongs_to :store
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :nickname
  # attr_accessible :title, :body
  has_many :store_favorites
  has_many :stores, :through => :store_favorites
  
  def add_store(store)
    favorites=store_favorites.build(:store_id => store.id)
    if !favorites.save
      logger.debug "Company '#{store.company}' already exists in your favorites."
    end
  end
  

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
  
  def favorites
    @favorites = current_user.stores
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fatwallet</title>
  <%= stylesheet_link_tag    "application", "bootstrap-responsive.css", "bootstrap.css", :media => "all" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <%= javascript_include_tag "application","bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
	<div class='well'>	
	
		<div class='homelogo'>
			<%= link_to image_tag('rails.png', :alt =>'logo'), posts_path%>
		</div>
	
		<div class='header'<>
			<h1><em>Fatwallet.com</em></h1>
			<p>A dollar saved is a dollar earned</p>
		</div>
	
		<div class='login floatright'>
		  <% if user_signed_in? %>
		    <%= current_user.firstname%> |
		    <%= link_to current_user.email, edit_user_registration_path %> |
		    <%= link_to "My Wish List", '#' %> |
		    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> | 
		    <%= link_to "Need Help", '#' %>
		  <% else %>
		    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
		  <% end %>
		</div>
		
		<div class='clear'></div>
		
		<form class='form-search myform'>
			<input type='text' class='input-medium search-query'>
			<button type='submit' class='btn'>Search</button>
		</form>
	
	</div>
	
	<div><em>
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %></em>
	</div>
	
	<div class='container'>
		</br>
		<div class='span12'>
			<% if user_signed_in? %>
			<ul class='nav nav-tabs'>
				<li class='dropdown active'>
					<a href='#' class='dropdown-toggle' data-toggle='dropdown'>Forum<b class='caret'></b></a>				
					<ul class='dropdown-menu'>
						<li><%= link_to 'Hot Deals', posts_path %></li>
						<li><%= link_to 'New', new_post_path %></li>
					</ul>
				</li>
				<li class='dropdown active'>
					<a href='#' class='dropdown-toggle' data-toggle='dropdown'>Cash Back Stores<b class='caret'></b></a>				
					<ul class='dropdown-menu'>
						<li><%= link_to 'All Stores', stores_path %></li>
					</ul>
				</li>
				<li class='active'><%= link_to 'My Favorites', :controller => :stores, :action => :favorites %></li>	
				<li class='active'><%= link_to 'Sales', '#' %></li>		

			</ul>
			<% end %>
		</div>
		
		<div class='span12'>
			<%= yield %>
		</div>
	</div>
	
	<div class='footer'>
		<p>copyright ©2012</p>
	</div>
	
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.user %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>User:</b>
  <%= @post.user %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :cashback %><br />
    <%= f.text_field :cashback %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/favorites.html.erb
<p id="notice"><%= notice %></p>

<p>
<% @favorites.each do |i| %>
<%= i.company %>
<% end %>
</p>


<%= link_to 'Edit', '#' %> |
<%= link_to 'Back', '#' %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Cashback</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stores.each do |store| %>
  <tr>
    <td><%= store.company %></td>
    <td><%= store.cashback %></td>
    <td><%= link_to 'Show', store %></td>
    <td><%= link_to 'Edit', edit_store_path(store) %></td>
    <td><%= link_to 'Destroy', store, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @store.company %>
</p>

<p>
  <b>Cashback:</b>
  <%= @store.cashback %>
</p>


<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>